#!/bin/bash

ORIGIN_PWD=${PWD}

help="hybridmeter_dev, the all-in-one tool for continuous integration of hybridmeter
     \n\nUsage : hybridmeter_dev [-help|-h] [--] <autostage|stage|build|auto_config MOODLE_ROOT> 
     \n\nautoconfig MOODLE_ROOT\tAdd moodle root path and git root path in the hybrid_dev.env file
     \nautostage\t\tStage changes to local moodle immediately and when they are changes in the codebase
     \nbuild\t\t\tBuild ZIP file of the plugin for deployment
     \nstage\t\t\tStage changes to local moodle only once
     \n\nOptions :
     \n\t--help|-h\tDisplay this screen
     \n\n2022 ISAE-Supaero"

in_options=1
while [ $# -gt 0 ] && [ $in_options -eq 1 ]
do
    case $1 in
    --help | -h)
        echo -e $help
        exit 0
        shift
        ;;
    --)
        in_options=0
        shift
        ;;
    -*)
        echo -e $help>&2
        exit 1
        ;;
    *)
        in_options=0
        ;;
    esac
done

SCRIPT_PATH=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT_PATH)

. ${SCRIPT_DIR}/hybrid_dev.env

git_root_undefined=0
moodle_root_undefined=0

if [ -d "${HYBRIDMETER_GIT_ROOT}" ]
then
    SOURCE_PATH="${HYBRIDMETER_GIT_ROOT}/hybridmeter"
    DEVTOOLS_PATH="${HYBRIDMETER_GIT_ROOT}/devtools"
    VUE_PATH="${SOURCE_PATH}/vue"
else
    git_root_undefined=1
fi

if [ -d "${HYBRIDMETER_MOODLE_ROOT}" ]
then
    MOODLE_ROOT=${HYBRIDMETER_MOODLE_ROOT}
    REPORT_PATH="${MOODLE_ROOT}/report"
    HYBRIDMETER_PATH="${REPORT_PATH}/hybridmeter"
else
    moodle_root_undefined=1
fi

if [ "$1" = "autoconfig" ]
then
    shift

    if [ $# -eq 0 ]
    then
        echo -e $help>&2
        exit 1
    fi

    if [ ! -d $1 ]
    then
        echo "$1 isn't a valid folder path">&2
        exit 3
    fi

    moodle_root=$(readlink -f $1)
    git_root=$(readlink -f "${SCRIPT_DIR}/../")
    env_file="${SCRIPT_DIR}/hybrid_dev.env"

    if [ -f ${env_file} ]
    then
        sed '/HYBRIDMETER_MOODLE_ROOT/d' ${env_file} > ${env_file}
        sed '/HYBRIDMETER_GIT_ROOT/d' ${env_file} > ${env_file}
    else
        touch ${env_file}
    fi

    echo "HYBRIDMETER_MOODLE_ROOT=\"${moodle_root}\"" >> ${env_file}
    echo "HYBRIDMETER_GIT_ROOT=\"${git_root}\"" >> ${env_file}

    echo "Environment ready"
    exit 0
fi

if [ $git_root_undefined -eq 1 ]
    then
        echo "[ERROR] The git root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH">&2
        exit 2
    elif [ $moodle_root_undefined -eq 1 ]
    then
        echo "[ERROR] The moodle root path isn't defined or isn't valid, please execute ./hybridemeter_dev autoconfig MOODLE_ROOT_PATH">&2
        exit 3
fi

if [ "$1" = "autostage" ]
then
    while true
    do
        find ${SOURCE_PATH} -not -path "*hybridmeter/vue/node_modules*" | entr -dr bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
        #TODO : forcer à recharger la page avec xdotool
    done
    exit 0
elif [ "$1" = "stage" ]
then
    bash ${DEVTOOLS_PATH}/stage_to_moodle.sh ${SOURCE_PATH} ${REPORT_PATH} ${VUE_PATH}
    error_code=$?
    if [ $error_code -ne 0 ]
    then
        echo "[ERROR] An error occured during the stage, error code ${error_code}">&2
        exit 4
    fi
elif [ "$1" = "build" ]
then
    cd ${VUE_PATH} && npm run build && cd ${OLDPWD}
    
    error_code=$?
    if [ $error_code -ne 0 ]
    then
        "[ERROR] An error occured during the webpacking, error code ${error_code}">&2
        cd ${ORIGIN_PWD}
        exit 5
    fi

    if [ -f "${GIT_ROOT}/report_hybridmeter.zip" ]
    then
        rm "${GIT_ROOT}/report_hybridmeter.zip"
    fi
    cd ${SOURCE_PATH} && zip -r "${GIT_ROOT}/report_hybridmeter.zip" . -x "vue/*" && cd ${OLDPWD}

    error_code=$?
    if [ $error_code -eq 0 ]
    then
        echo "[SUCCESS] Plugin successfully built"
        exit 0
    else
        cd ${ORIGIN_PWD}
        echo "[ERROR] An error occured during the building of the zip file, error code ${error_code}">&2
        exit 5
    fi
else
    echo -e $help>&2
    exit 1
fi
